// Mechanically extracts every table the C engine needs straight out of game.js.
// Nothing here is retyped: PIECES / PROMOTE / VALUES / VALUES_PROMOTED and the initial
// board are produced by executing the reference code, and White orientations come from
// calling the reference invert_color().
const fs = require('fs')
const vm = require('vm')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const sandbox = { console, alert: (m) => { throw new Error('alert: ' + m) } }
vm.createContext(sandbox)
const src = fs.readFileSync(path.join(ROOT, 'game.js'), 'utf8')
// `const` at the top level of a vm script stays lexical, so hand the bindings back out.
const { PIECES, PROMOTE, VALUES, VALUES_PROMOTED, Board } = vm.runInContext(
    src + '\n;({ PIECES, PROMOTE, VALUES, VALUES_PROMOTED, Board })', sandbox, { filename: 'game.js' })

const ids = Object.keys(PIECES).map(Number).sort((a, b) => a - b)
const idx_of = new Map(ids.map((id, i) => [i, id].reverse()))
const N = ids.length

// ---- special-case dispatch, keyed exactly as game.js keys it ----------------
function special_of(id) {
    if (id === 276) return 'SP_FREE_EAGLE'
    if (id === 286 || id === 289) return 'SP_TRAMPLE_ORTHO'
    if (id === 287 || id === 288 || id === 290) return 'SP_TRAMPLE_DIAG'
    if (id === 291) return 'SP_TRAMPLE_ALL'
    if (id === 292) return 'SP_HOOK_ORTHO'
    if (id === 293 || id === 294) return 'SP_HOOK_DIAG'
    if (id === 295) return 'SP_PEACOCK'
    if (id >= 297 && id <= 300) return 'SP_LION'
    return 'SP_NONE'
}

// ---- resolve each (id, colour) through the reference code -------------------
const tp_pool = []          // flattened {dx,dy,slide[8]}
const defs = []             // indexed by idx*2 + color

for (const id of ids) {
    for (const color of [0, 1]) {
        const p = PIECES[id].copy(0, 0)
        if (color === 0) p.invert_color()
        if (p.color !== color) throw new Error('colour resolve failed for ' + id)
        const tp_off = tp_pool.length
        for (const e of p.tp) {
            if (e.length !== 3 || !Number.isInteger(e[0]) || !Number.isInteger(e[1]) || e[2].length !== 8)
                throw new Error(`malformed tp entry on id ${id}: ${JSON.stringify(e)}`)
            tp_pool.push([e[0], e[1], e[2].slice()])
        }
        if (p.dydx.length !== 8 || p.djump.length !== 8) throw new Error('bad arity on id ' + id)
        defs[idx_of.get(id) * 2 + color] = {
            id, color, name: p.name, level: p.level,
            dydx: p.dydx.slice(), djump: p.djump.slice(),
            tp_off, tp_n: p.tp.length,
            special: special_of(id),
        }
    }
}

// ---- values (fixed point, 1/1000 pawn) -------------------------------------
const FP = 1000
function fx(v) {
    const s = Math.round(v * FP)
    if (Math.abs(s / FP - v) > 1e-9) throw new Error('value ' + v + ' not representable')
    return s
}
// material_value(piece) verbatim, but the King is excluded from the balance: both sides
// hold exactly one in every non-terminal position, so it contributes nothing but noise.
function mat(id, promoted) {
    if (id === 1000) return 0
    const v = (promoted && VALUES_PROMOTED[id] !== undefined) ? VALUES_PROMOTED[id] : VALUES[id]
    if (v === undefined) throw new Error('no value for id ' + id)
    return fx(v)
}

// ---- initial board ---------------------------------------------------------
const b = new Board()
const init = []
for (let x = 0; x < 36; x++) for (let y = 0; y < 36; y++) {
    const p = b.board[x][y]
    if (p.x !== x || p.y !== y) throw new Error('coordinate desync at ' + x + ',' + y)
    init.push([idx_of.get(p.id), p.color, p.promoted ? 1 : 0])
}

// ---- promotion, resolved to indices ----------------------------------------
const promote_idx = ids.map((id) => (PROMOTE[id] !== undefined ? idx_of.get(PROMOTE[id]) : -1))

// ---- emit ------------------------------------------------------------------
const L = []
const w = (s) => L.push(s)
const arr = (a) => a.join(',')

w('// GENERATED by engine/gen_tables.js from game.js. Do not edit.')
w('#ifndef TKY_TABLES_H')
w('#define TKY_TABLES_H')
w('#include <stdint.h>')
w('')
w(`#define NPIECE ${N}`)
w(`#define NDEF   ${N * 2}`)
w(`#define EMPTY_IDX ${idx_of.get(0)}`)
w(`#define KING_IDX  ${idx_of.get(1000)}`)
w(`#define VALUE_FP  ${FP}`)
w('')
w('enum { SP_NONE=0, SP_FREE_EAGLE, SP_TRAMPLE_ORTHO, SP_TRAMPLE_DIAG, SP_TRAMPLE_ALL,')
w('       SP_HOOK_ORTHO, SP_HOOK_DIAG, SP_PEACOCK, SP_LION };')
w('')
w('typedef struct { int8_t dx, dy; uint8_t slide[8]; } TpEntry;')
w('typedef struct {')
w('    uint8_t  dydx[8];')
w('    uint8_t  djump[8];')
w('    uint16_t tp_off;')
w('    uint8_t  tp_n;')
w('    uint8_t  special;')
w('    uint8_t  level;')
w('    uint8_t  color;')
w('    uint16_t id;')
w('    uint8_t  has_djump;   /* any djump[d] != 0 */')
w('    uint8_t  simple;      /* SP_NONE, no tp, no djump: pure slider/stepper */')
w('} PieceDef;')
w('')
w(`static const TpEntry TP_POOL[${Math.max(1, tp_pool.length)}] = {`)
if (tp_pool.length === 0) w('  {0,0,{0,0,0,0,0,0,0,0}}')
else for (const [dx, dy, s] of tp_pool) w(`  {${dx},${dy},{${arr(s)}}},`)
w('};')
w('')
w(`static const PieceDef DEFS[NDEF] = {`)
for (let i = 0; i < defs.length; i++) {
    const d = defs[i]
    const has_dj = d.djump.some((v) => v !== 0) ? 1 : 0
    const simple = (d.special === 'SP_NONE' && d.tp_n === 0 && !has_dj) ? 1 : 0
    w(`  {{${arr(d.dydx)}},{${arr(d.djump)}},${d.tp_off},${d.tp_n},${d.special},${d.level},${d.color},${d.id},${has_dj},${simple}}, /* ${i} ${d.name} ${d.color ? 'B' : 'W'} */`)
}
w('};')
w('')
w('/* code = idx*4 | color*2 | promoted */')
w(`static const int32_t MATVAL[${N * 4}] = {`)
{
    const v = []
    for (const id of ids) for (const color of [0, 1]) for (const pr of [0, 1]) v.push(mat(id, pr === 1))
    for (let i = 0; i < v.length; i += 16) w('  ' + v.slice(i, i + 16).join(',') + ',')
}
w('};')
w('')
w(`static const int16_t PROMOTE_IDX[${N}] = {`)
for (let i = 0; i < promote_idx.length; i += 20) w('  ' + promote_idx.slice(i, i + 20).join(',') + ',')
w('};')
w('')
w('/* initial position, x*36+y, as packed codes */')
w('static const uint16_t INIT_BOARD[1296] = {')
for (let i = 0; i < init.length; i += 18) {
    w('  ' + init.slice(i, i + 18).map(([ix, c, pr]) => (ix << 2) | (c << 1) | pr).join(',') + ',')
}
w('};')
w('')
w(`static const char *const PIECE_NAME[${N}] = {`)
for (const id of ids) w(`  ${JSON.stringify(PIECES[id].name)},`)
w('};')
w(`static const uint16_t PIECE_ID[${N}] = {${ids.join(',')}};`)
w('')
w('#endif')

fs.writeFileSync(path.join(__dirname, 'tables.h'), L.join('\n') + '\n')

// A JSON copy so other tooling (and the validator) can use the same source of truth.
fs.writeFileSync(path.join(__dirname, 'tables.json'), JSON.stringify({
    ids, defs, tp_pool, promote_idx, init, N,
    values: Object.fromEntries(ids.map((id) => [id, [mat(id, false), mat(id, true)]])),
}))

console.log(`ids=${N} defs=${defs.length} tp_entries=${tp_pool.length}`)
console.log(`occupied at start=${init.filter((e) => e[0] !== idx_of.get(0)).length}`)
